### ISSUE TITLE
How to change video stream size written by MediaRecorder?

### ISSUE THREAD

**Issue by aniongithub** [aiortc/aiortc#183]
When using cli.py from the "videostream-cli" sample, I can't get the video stream to transmit/save at any resolution other than 640x480.

I see a few places in "aiortc/mediastreams.py" where this is hardcoded, but even changing them to my video sizes didn't seem to work.

**Comment by jlaine** [comment]
The *written* size will be whatever you are receiving from the remote party, so no changes are required here.

Regarding what is sent : the "flag" example is indeed fixed at 640x480, but that's not all you can send. If you use the `--play-from` command line option you can send any video file, and it will be sent without resizing.

As for the hard-coded dimensions in `aiortc/mediastreams.py` you don't need to worry about them, they are purely for the case where you are not sending anything at all, i.e. instantiating `VideoStreamTrack` directly. This could possibly be moved to a `DummVideoStreamTrack` but I'm not sure it's worth the trouble.

**Comment by aniongithub** [comment]
Unfortunately, this is NOT right.

I tried it with this video

`wget 'http://downloads.4ksamples.com/videos/PUPPIES%20BATH%20IN%204K%20(ULTRA%20HD)(Original_H.264-AAC)%20(4ksamples.com).mp4' -O 'puppies.mp4'`

and then ran two peers using  

`videostream-cli/cli.py offer --play-from 'puppies.mp4'`
`videostream-cli/cli.py answer --record-to 'received.mp4'`

After some of the video is transmitted and written to disk, Ctrl+C those processes and try

`ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 puppies.mp4`
which should be 4096x2304 and then run
`ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 received.mp4`
which always returns 640x480

Am I missing something?

**Comment by aniongithub** [comment]
*bump* - Any help is appreciated, I still can't use videostream-cli to transmit (or at least save) videos at any size other than 640x480.

**Comment by jlaine** [comment]
I tried the "puppies" example and indeed the frames **written** out to the file seem to be 640x480.

However if I add a `print(frame)` just before this line:

https://github.com/aiortc/aiortc/blob/004431cef43553308023a6560149b5e2f15b98be/aiortc/contrib/media.py#L375

.. and I see:

```
<av.VideoFrame #0, pts=0 yuv420p 4096x2304 at 0x7f9c361b93a8>
<av.VideoFrame #1, pts=2 yuv420p 4096x2304 at 0x7f9c361b92e8>
<av.VideoFrame #2, pts=4 yuv420p 4096x2304 at 0x7f9c361b9468>
<av.VideoFrame #3, pts=6 yuv420p 4096x2304 at 0x7f9c361b9408>
...
```

This shows that the frames are correctly sent and received with the original dimensions (4096x2304). The switch to 640x480 is occuring when writing out the file, specifically when adding the stream to the output file:

https://github.com/aiortc/aiortc/blob/004431cef43553308023a6560149b5e2f15b98be/aiortc/contrib/media.py#L340

The reason is that PyAV sets a default of 640x480:

https://github.com/mikeboers/PyAV/blob/cd458ffe89988b0feca44da6c56ef29f17555962/av/container/output.pyx#L97

As a workaround you can add:

```patch
diff --git a/aiortc/contrib/media.py b/aiortc/contrib/media.py
index ca3cfa4..654d52a 100644
--- a/aiortc/contrib/media.py
+++ b/aiortc/contrib/media.py
@@ -339,6 +339,8 @@ class MediaRecorder:
             else:
                 stream = self.__container.add_stream("libx264", rate=30)
                 stream.pix_fmt = "yuv420p"
+                stream.width = 4096
+                stream.height = 2304
         self.__tracks[track] = MediaRecorderContext(stream)
 
     async def start(self):
```

I'm not sure how to do this automatically though, as we don't know the dimensions ahead of time, only once the first frames are received.

**Comment by aniongithub** [comment]
Thanks! I believe the MediaTrack exposes the width and height of the stream as it's added?

https://chromium.googlesource.com/external/webrtc/+/3c1e558449309be965815e1bf/webrtc/api/mediastreaminterface.h#118

**Comment by jlaine** [comment]
To my knowledge the only way you get the width / height is once you start receiving data. This is problematic as `MediaRecorder` initialises the stream as soon as you add it, so I think it would mean deferring adding the pyav stream until the first frame is received.

**Comment by arpu** [comment]
Hello i hit the same problem. hardcoding the stream with/height in media.py  works. 
any hint how i can set this from  the frame i get <av.VideoFrame #2149, pts=14541750 yuv420p 2560x1440 at 0x7fc7be239360>  on https://github.com/aiortc/aiortc/blob/master/src/aiortc/contrib/media.py#L378

**Comment by ashkov** [comment]
Hi, @jlaine !
Do you consider to add `**kwargs` to `MediaRecorder.addTrack`, where we can specifiy 
```
                if 'width' in kwargs:
                    stream.width = kwargs['width']
                if 'height' in kwargs:
                    stream.height = kwargs['height']
```

**Comment by claurans** [comment]
> I'm not sure how to do this automatically though, as we don't know the dimensions ahead of time, only once the first frames are received.

For anyone else looking for this, just thought I'd note that I did exactly what @jlaine suggested there and automatically set width and height on first frame. This could be improved by not setting the width and height on every frame, just the first one, but you get the idea:

```
    async def __run_track(self, track, context):
        assert self.__container is not None
        while True:
            try:
                frame = await track.recv()
            except MediaStreamError:
                return
            if track.kind == "video":
                context.stream.width = frame.width
                context.stream.height = frame.height
            for packet in context.stream.encode(frame):
                self.__container.mux(packet)
```
